# Generated by Django 3.1.3 on 2020-11-05 07:26

from django.db import migrations, models
import main.utils.accounts


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_edited', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.utils.accounts.UserManager()),
            ],
        ),
    ]
