# Generated by Django 3.1.3 on 2020-11-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201105_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='index',
        ),
    ]
