# Generated by Django 3.1.4 on 2021-01-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210107_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='old_price',
        ),
    ]
