# Generated by Django 3.1.4 on 2021-01-07 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210107_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='initial_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='deal',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 15, 0, 46, 473086), null=True),
        ),
    ]
