# Generated by Django 3.1.4 on 2021-01-07 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210107_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='initial_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='deal',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
