# Generated by Django 3.1.4 on 2021-01-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210107_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='initial_price',
        ),
    ]
