# Generated by Django 3.1.4 on 2021-01-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210107_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='initial_price',
            new_name='market_price',
        ),
    ]
