# Generated by Django 3.1.4 on 2021-01-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210115_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(editable=False, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='banner_ads')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'ordering': ['-pk', 'date', 'title'],
            },
        ),
    ]
