# Generated by Django 3.1.4 on 2021-01-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_bannerad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerad',
            options={},
        ),
        migrations.RemoveField(
            model_name='bannerad',
            name='date',
        ),
    ]
