# Generated by Django 3.1.4 on 2021-01-25 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20210125_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerad',
            options={'ordering': ['-pk', 'date', 'title']},
        ),
        migrations.AddField(
            model_name='bannerad',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
