# Generated by Django 3.1.4 on 2021-02-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_bannerad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerad',
            name='show_prices',
            field=models.BooleanField(default=True),
        ),
    ]
