# Generated by Django 3.1.4 on 2021-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_bannerad_show_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='image',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
