# Generated by Django 3.1.4 on 2021-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210206_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerad',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
