# Generated by Django 3.1.4 on 2021-02-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_bannerad_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
