# Generated by Django 3.1.4 on 2021-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20210209_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerad',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='bannerad',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='banners/thumbnails/'),
        ),
    ]
